// DesignTokens.swift
// Yarn&Yarn
//
// AUTO-GENERATED — do not edit this file by hand.
// Source of truth: tokens/tokens.json
// Regenerate with: python3 scripts/generate_swift.py

import SwiftUI

enum DesignTokens {

    // MARK: - Colors

    enum Colors {

        /// Named palette for counter marker badges
        enum Counter {
            static let sage         = Color(red: 0.48, green: 0.68, blue: 0.56)
            static let mauve        = Color(red: 0.75, green: 0.52, blue: 0.66)
            static let terracotta   = Color(red: 0.83, green: 0.45, blue: 0.35)
            static let steel        = Color(red: 0.42, green: 0.61, blue: 0.75)
            static let gold         = Color(red: 0.83, green: 0.66, blue: 0.26)
            static let lavender     = Color(red: 0.61, green: 0.56, blue: 0.77)
            static let forest       = Color(red: 0.42, green: 0.56, blue: 0.37)
            static let rose         = Color(red: 0.91, green: 0.65, blue: 0.65)
            static let slate        = Color(red: 0.48, green: 0.56, blue: 0.65)
            static let amber        = Color(red: 0.79, green: 0.42, blue: 0.18)
            static let plum         = Color(red: 0.48, green: 0.31, blue: 0.45)
            static let linen        = Color(red: 0.78, green: 0.72, blue: 0.60)

            /// All counter colors in palette order
            static let all: [(name: String, color: Color)] = [
                ("sage", sage), ("mauve", mauve), ("terracotta", terracotta),
                ("steel", steel), ("gold", gold), ("lavender", lavender),
                ("forest", forest), ("rose", rose), ("slate", slate),
                ("amber", amber), ("plum", plum), ("linen", linen)
            ]

            /// Returns `.white` for dark counter backgrounds, `.black` for light ones.
            static func textColor(for name: String) -> Color {
                name == "plum" ? .white : .black
            }

            /// Looks up a counter color by name, falling back to sage.
            static func color(named name: String) -> Color {
                all.first { $0.name == name }?.color ?? sage
            }
        }

        /// Project status indicator colors
        enum Status {
            static let notStarted: Color = .secondary  // iOS system secondary grey
            static let inProgress: Color = .accentColor  // iOS system blue / accent
            static let onHold: Color = .orange  // iOS system orange
            static let completed: Color = .green  // iOS system green
        }

        /// Glossary category badge colors
        enum Category {
            static let basicStitches: Color = .yellow  // Yellow — basic stitches
            static let increasesDecreases: Color = .orange  // Orange — increases & decreases
            static let castOnBindOff: Color = .green  // Green — cast on & bind off
            static let cables: Color = .purple  // Purple — cables
            static let colorwork: Color = .pink  // Pink — colorwork
            static let lace: Color = .cyan  // Cyan — lace
            static let `default`: Color = .blue  // Blue — all other categories
        }

        /// Legacy note marker colors
        enum Marker {
            static let blue: Color = .blue
            static let green: Color = .green
            static let red: Color = .red
            static let yellow: Color = .orange  // orange for better contrast
            static let purple: Color = .purple

            static func color(named name: String) -> Color {
                switch name {
                case "blue": return blue
                case "green": return green
                case "red": return red
                case "yellow": return yellow
                case "purple": return purple
                default:       return blue
                }
            }
        }
    }

    // MARK: - Typography

    enum Typography {
        /// Font size scale (points)
        static let sizeXS: CGFloat = 10  // Smallest label text (monospaced PDF)
        static let sizeSM: CGFloat = 12  // Caption / min reader size
        static let sizeBase: CGFloat = 14  // Standard detail text
        static let sizeMD: CGFloat = 16  // Body / base reader font
        static let sizeLG: CGFloat = 18  // Section headers
        static let sizeXL: CGFloat = 22  // Tool tab icons / counter display
        static let sizeXXL: CGFloat = 36  // Large display text
        static let sizeHero: CGFloat = 48  // Hero numbers (glossary detail)
    }

    // MARK: - Spacing

    enum Spacing {
        static let xs: CGFloat = 4
        static let sm: CGFloat = 6
        static let md: CGFloat = 8
        static let lg: CGFloat = 12
        static let xl: CGFloat = 16
        static let xxl: CGFloat = 20
        static let xxxl: CGFloat = 24
        static let max: CGFloat = 30
    }

    // MARK: - Radius

    enum Radius {
        static let xs: CGFloat = 4  // text highlights, small chips
        static let sm: CGFloat = 8  // text fields, small elements
        static let md: CGFloat = 10  // search bar
        static let lg: CGFloat = 12  // cards, buttons, backgrounds
    }

    // MARK: - Shadow

    enum Shadow {
        enum Standard {
            static let opacity: Double = 0.2
            static let radius: CGFloat = 4
            static let y: CGFloat = 2
        }
        enum Accent {
            static let opacity: Double = 0.35
            static let radius: CGFloat = 12
            static let y: CGFloat = 5
        }
    }
}
